Feat/improve display supported blockchains
LedgerHQ/wallet-connect-live-app pull request #166
Opened 2024-05-16 09:21 UTC by Wozacosta

### 📝 Description

_Replace this text by a clear and concise description of what this pull request is about and why it is needed._

### ❓ Context

- **Linked resource(s)**: [] 

### 📸 Demo

### 🚀 Expectations to reach

_Pull Requests must pass the CI and be internally validated in order to be merged._

2024-05-22 13:00 UTC, RamyEB requested changes

2024-05-22 15:21 UTC, Wozacosta commented on src/components/atoms/AccountBalance.tsx
> +        {/* NOTE: is there an easy way to get $ (fiat) value of currency from liveapp */}
🧹

2024-05-22 15:21 UTC, Wozacosta commented on src/components/screens/SessionProposal.tsx
> +  console.log({ chainsWhereNoAccounts, accountsByChain });
nope, 🧹

2024-05-23 13:56 UTC, RamyEB submitted a review, later dismissed

2024-05-27 13:02 UTC, Justkant commented on src/components/screens/sessionProposal/LogoHeader.tsx
> +  }
nit pick to remove the else an rely on the early return
```suggestion
  }
  return (
    <LogoContainer>
      <WalletConnectMedium size={30} />
    </LogoContainer>
  );
```

2024-05-28 09:04 UTC, RamyEB approved these changes

2024-05-28 09:56 UTC, merged

2024-05-28 10:43 UTC, Justkant commented on src/hooks/useProposal/useProposal.ts
> +      }
This is not the only error possible we should show a toast here unless it's cancelled by the user by check the error