Add `Rootstock` chain
LedgerHQ/wallet-connect-live-app pull request #194
Opened 2024-10-14 17:38 UTC by ahsan-javaiid

# Description

This PR adds rootstock chain to the list of supported networks in wallet-connect-live-app. 

About Rootstock
Website: https://rootstock.io/
Defillama: https://defillama.com/chain/Rootstock
Explorer: https://explorer.rootstock.io/
Developer portal: https://dev.rootstock.io/

# Context

We are working on to enable wallet connect via ledger for Rootstock in https://github.com/LedgerHQ/ledger-live. For that, purpose we need this PR to be merged so that we can add support for Rootstock in ledger-live for wallet connect. 

## Type of change

- [X] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-10-14 17:39 UTC, ahsan-javaiid commented
@Justkant Would be great if you can review and consider this pull request. Feel free to suggest if any changes required.

2024-10-21 12:58 UTC, ahsan-javaiid commented
@Justkant We are working on to enable wallet connect for Rootstock in LedgerLive. This PR is required to be merged for this purpose. Let me know if you get a chance to review this pull request.

2024-10-22 15:23 UTC, Justkant requested changes
Thanks for the PR

I tested your PR and it was not working, the issue is only the currency name used in LL
Which is not `rootstock` but `rsk`, after apply my proposed changes everything seems to work correctly

We'll also have to update our manifest on the backend after merging this to make it work properly in prod

2024-10-22 15:23 UTC, Justkant commented on src/data/network.config.ts
> +  rootstock: {
```suggestion
  rsk: {
```

2024-10-22 15:23 UTC, Justkant commented on localManifest.json
> +    "rootstock",
```suggestion
    "rsk",
```

2024-10-22 15:23 UTC, Justkant commented on src/data/__tests__/networkConfig.test.ts
> +    const rootstock: Network | undefined = SUPPORTED_NETWORK.rootstock;
```suggestion
    const rootstock: Network | undefined = SUPPORTED_NETWORK.rsk;
```

2024-10-22 15:48 UTC, ahsan-javaiid commented on src/data/network.config.ts
> +  rootstock: {
Done!

2024-10-22 15:49 UTC, ahsan-javaiid commented on src/data/__tests__/networkConfig.test.ts
> +    const rootstock: Network | undefined = SUPPORTED_NETWORK.rootstock;
Done!

2024-10-23 07:50 UTC, Justkant approved these changes

2024-10-23 07:50 UTC, merged